import { Inter } from "next/font/google";
import "@/style/globals.css";
import Navbar from "@/components/Navbar";
import Cookies from "js-cookie";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "biroperjalanan Datacakra",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const token = Cookies.get('token');

  if(!token){}

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
